# ---------- Banco de dados (MySQL) ----------
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USER:portfolio}
quarkus.datasource.password=${DB_PASSWORD:portfolio}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/portfolio_db}
quarkus.hibernate-orm.database.generation=update

# ---------- JWT ----------

mp.jwt.verify.issuer=https://trending-products.local/issuer
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem


# duração do token (segundos)
jwt.duration.seconds=3600

# ---------- HTTP ----------
# ---------- HTTP ----------
quarkus.http.port=8080
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*

# ---------- Perfil de teste (H2 em memória) ----------
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.schema-management.strategy=update


# =========================================================
# OBSERVABILIDADE
# =========================================================

# Endpoint das métricas
quarkus.micrometer.export.prometheus.enabled=true

# Interface de gerenciamento
quarkus.management.enabled=true

# Permite acesso externo à interface de gerenciamento
quarkus.management.host-validation.require-localhost=false